### ISSUE TITLE
The service doesn't work

### ISSUE THREAD

**Issue by IsaacMonkimun** [ryandoom/mailchimp-post#1]
Hello,

I was using this service:

https://mailchimp-post.herokuapp.com/

It was working fine, but last 13 days, it doesn't work.

please, can you fix it?

thanks.

Isaac.

**Comment by hallmatt** [comment]
@IsaacMonkimun you'll have to go into more detail about the times that have failed for you. my indications are that everything is working fine. We have quite a few forms relying on this service and all seem to be working fine.

Are you using the MailChimp features? Constant Contact? Google Events?

**Comment by IsaacMonkimun** [comment]
I am doing a post in this url:
https://mailchimp-post.herokuapp.com/data/MY KEY
with parameters:
list_id=MY_LIST_ID&email=EMAIL&...
I have a app submitted, and it was working fine, but last 13 days, it doesn't work.

if i do this command:
curl https://mailchimp-post.herokuapp.com/data/xxxxxxxxxxxxxxxxxxxx-us8 -d "list_id=xxxxxxxxx&email=isaac@monkimun.es"

i am getting error 500.

**Comment by hallmatt** [comment]
I'm looking into this issue and hope to have some answers soon.

**Comment by hallmatt** [comment]
@IsaacMonkimun this issue should be fixed. thanks for your help!
